/* Gymmap / Soura Home Gym - Sports master data
   SQL Server compatible seed script.
   Sports are master records and should be selected from a dropdown in the admin panel.
*/

IF OBJECT_ID(N'dbo.Sports', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Sports (
        Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Sports PRIMARY KEY,
        NameFa NVARCHAR(100) NOT NULL,
        NameEn NVARCHAR(100) NULL,
        CategoryFa NVARCHAR(100) NOT NULL,
        IsActive BIT NOT NULL CONSTRAINT DF_Sports_IsActive DEFAULT (1),
        SortOrder INT NOT NULL CONSTRAINT DF_Sports_SortOrder DEFAULT (0),
        CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Sports_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT UQ_Sports_NameFa UNIQUE (NameFa)
    );
END;
GO

INSERT INTO dbo.Sports (NameFa, NameEn, CategoryFa, SortOrder)
SELECT v.NameFa, v.NameEn, v.CategoryFa, v.SortOrder
FROM (VALUES
(N'بدنسازی',N'Bodybuilding',N'بدنسازی و فیتنس',10),
(N'فیتنس',N'Fitness',N'بدنسازی و فیتنس',20),
(N'فانکشنال',N'Functional Training',N'بدنسازی و فیتنس',30),
(N'کراس‌فیت',N'CrossFit',N'بدنسازی و فیتنس',40),
(N'بوت‌کمپ',N'Bootcamp',N'بدنسازی و فیتنس',50),
(N'کالیستنیکس',N'Calisthenics',N'بدنسازی و فیتنس',60),
(N'کِتل‌بل',N'Kettlebell',N'بدنسازی و فیتنس',70),
(N'تمرینات TRX',N'TRX',N'بدنسازی و فیتنس',80),
(N'تمرینات مقاومتی',N'Resistance Training',N'بدنسازی و فیتنس',90),
(N'تمرینات HIIT',N'HIIT',N'بدنسازی و فیتنس',100),
(N'تمرینات هوازی',N'Aerobic Training',N'بدنسازی و فیتنس',110),
(N'استپ',N'Step Aerobics',N'بدنسازی و فیتنس',120),
(N'اسپینینگ',N'Spinning',N'بدنسازی و فیتنس',130),
(N'دوچرخه ثابت',N'Stationary Cycling',N'بدنسازی و فیتنس',140),
(N'پاورلیفتینگ',N'Powerlifting',N'قدرتی',150),
(N'وزنه‌برداری',N'Weightlifting',N'قدرتی',160),
(N'تمرینات قدرتی',N'Strength Training',N'قدرتی',170),
(N'یوگا',N'Yoga',N'یوگا و ذهن‌آگاهی',180),
(N'پاور یوگا',N'Power Yoga',N'یوگا و ذهن‌آگاهی',190),
(N'هات یوگا',N'Hot Yoga',N'یوگا و ذهن‌آگاهی',200),
(N'یین یوگا',N'Yin Yoga',N'یوگا و ذهن‌آگاهی',210),
(N'آشتانگا یوگا',N'Ashtanga Yoga',N'یوگا و ذهن‌آگاهی',220),
(N'هاثا یوگا',N'Hatha Yoga',N'یوگا و ذهن‌آگاهی',230),
(N'آینگار یوگا',N'Iyengar Yoga',N'یوگا و ذهن‌آگاهی',240),
(N'مدیتیشن',N'Meditation',N'یوگا و ذهن‌آگاهی',250),
(N'پیلاتس',N'Pilates',N'پیلاتس و اصلاحی',260),
(N'پیلاتس ریفورمر',N'Reformer Pilates',N'پیلاتس و اصلاحی',270),
(N'بارِه',N'Barre',N'پیلاتس و اصلاحی',280),
(N'حرکات اصلاحی',N'Corrective Exercise',N'پیلاتس و اصلاحی',290),
(N'تمرینات کششی',N'Stretching',N'پیلاتس و اصلاحی',300),
(N'موبیلیتی',N'Mobility',N'پیلاتس و اصلاحی',310),
(N'ژیمناستیک',N'Gymnastics',N'ژیمناستیک',320),
(N'ژیمناستیک ریتمیک',N'Rhythmic Gymnastics',N'ژیمناستیک',330),
(N'آکروباتیک',N'Acrobatics',N'ژیمناستیک',340),
(N'بانجی فیتنس',N'Bungee Fitness',N'فیتنس هوایی',350),
(N'پارکور',N'Parkour',N'فیتنس هوایی و مهارتی',360),
(N'رقص',N'Dance',N'رقص',370),
(N'زومبا',N'Zumba',N'رقص و هوازی',380),
(N'زومبا فیتنس',N'Zumba Fitness',N'رقص و هوازی',390),
(N'هیپ‌هاپ',N'Hip Hop',N'رقص',400),
(N'باله',N'Ballet',N'رقص',410),
(N'رقص معاصر',N'Contemporary Dance',N'رقص',420),
(N'رقص لاتین',N'Latin Dance',N'رقص',430),
(N'سالسا',N'Salsa',N'رقص',440),
(N'باچاتا',N'Bachata',N'رقص',450),
(N'رقص ایرانی',N'Persian Dance',N'رقص',460),
(N'ایروبیک',N'Aerobics',N'هوازی',470),
(N'فیت‌دنس',N'Fit Dance',N'هوازی و رقص',480),
(N'بوکس',N'Boxing',N'رزمی',490),
(N'کیک‌بوکسینگ',N'Kickboxing',N'رزمی',500),
(N'موی‌تای',N'Muay Thai',N'رزمی',510),
(N'کاراته',N'Karate',N'رزمی',520),
(N'تکواندو',N'Taekwondo',N'رزمی',530),
(N'جودو',N'Judo',N'رزمی',540),
(N'جوجیتسو',N'Jiu-Jitsu',N'رزمی',550),
(N'کشتی',N'Wrestling',N'رزمی',560),
(N'آیکیدو',N'Aikido',N'رزمی',570),
(N'کونگ‌فو',N'Kung Fu',N'رزمی',580),
(N'ووشو',N'Wushu',N'رزمی',590),
(N'شمشیربازی',N'Fencing',N'رزمی و مهارتی',600),
(N'شنا',N'Swimming',N'آبی',610),
(N'واترپلو',N'Water Polo',N'آبی',620),
(N'آب‌درمانی',N'Aquatic Therapy',N'آبی و درمانی',630),
(N'آکوا فیتنس',N'Aqua Fitness',N'آبی و هوازی',640),
(N'دویدن',N'Running',N'دو و استقامت',650),
(N'دو سرعت',N'Sprinting',N'دو و استقامت',660),
(N'دو استقامت',N'Distance Running',N'دو و استقامت',670),
(N'دوچرخه‌سواری',N'Cycling',N'دوچرخه‌سواری',680),
(N'دوچرخه‌سواری کوهستان',N'Mountain Biking',N'دوچرخه‌سواری',690),
(N'دوچرخه‌سواری جاده',N'Road Cycling',N'دوچرخه‌سواری',700),
(N'تنیس',N'Tennis',N'راکتی',710),
(N'پدل',N'Padel',N'راکتی',720),
(N'بدمینتون',N'Badminton',N'راکتی',730),
(N'تنیس روی میز',N'Table Tennis',N'راکتی',740),
(N'اسکواش',N'Squash',N'راکتی',750),
(N'والیبال',N'Volleyball',N'توپی',760),
(N'والیبال ساحلی',N'Beach Volleyball',N'توپی',770),
(N'بسکتبال',N'Basketball',N'توپی',780),
(N'فوتبال',N'Football',N'توپی',790),
(N'فوتسال',N'Futsal',N'توپی',800),
(N'هندبال',N'Handball',N'توپی',810),
(N'گلف',N'Golf',N'توپی',820),
(N'بولینگ',N'Bowling',N'تفریحی و توپی',830),
(N'اسکی',N'Skiing',N'زمستانی',840),
(N'اسنوبرد',N'Snowboarding',N'زمستانی',850),
(N'اسکیت',N'Skating',N'اسکیت',860),
(N'اسکیت روی یخ',N'Ice Skating',N'اسکیت',870),
(N'اسکیت سرعت',N'Speed Skating',N'اسکیت',880),
(N'کوهنوردی',N'Mountaineering',N'فضای باز',890),
(N'سنگ‌نوردی',N'Rock Climbing',N'فضای باز',900),
(N'صخره‌نوردی داخل سالن',N'Indoor Climbing',N'فضای باز و سالن',910),
(N'پیاده‌روی',N'Walking',N'فضای باز',920),
(N'های‌کینگ',N'Hiking',N'فضای باز',930),
(N'کایاک',N'Kayaking',N'ورزش‌های آبی',940),
(N'قایقرانی',N'Rowing',N'ورزش‌های آبی',950),
(N'کانو',N'Canoeing',N'ورزش‌های آبی',960),
(N'کایت‌سواری',N'Kitesurfing',N'ورزش‌های آبی',970),
(N'موج‌سواری',N'Surfing',N'ورزش‌های آبی',980),
(N'اسکواش آبی',N'Water Sports',N'ورزش‌های آبی',990),
(N'تیراندازی با کمان',N'Archery',N'مهارتی',1000),
(N'تیراندازی',N'Sport Shooting',N'مهارتی',1010),
(N'شطرنج',N'Chess',N'فکری',1020),
(N'دارت',N'Darts',N'مهارتی',1030),
(N'یوگا برای بانوان باردار',N'Prenatal Yoga',N'تخصصی بانوان',1040),
(N'فیتنس سالمندان',N'Senior Fitness',N'تخصصی',1050),
(N'فیتنس کودکان',N'Kids Fitness',N'تخصصی کودکان',1060),
(N'فیتنس نوجوانان',N'Teen Fitness',N'تخصصی نوجوانان',1070),
(N'ورزش پس از زایمان',N'Postnatal Fitness',N'تخصصی بانوان',1080),
(N'تمرینات بانوان',N'Women Fitness',N'تخصصی بانوان',1090),
(N'فیتنس سالم',N'Healthy Fitness',N'سلامت و تندرستی',1100),
(N'تمرینات تعادلی',N'Balance Training',N'سلامت و تندرستی',1110),
(N'تمرینات تنفسی',N'Breathing Exercises',N'سلامت و تندرستی',1120)
) v(NameFa,NameEn,CategoryFa,SortOrder)
WHERE NOT EXISTS (SELECT 1 FROM dbo.Sports s WHERE s.NameFa = v.NameFa);
GO

-- Dropdown query for the admin panel
SELECT Id, NameFa, NameEn, CategoryFa
FROM dbo.Sports
WHERE IsActive = 1
ORDER BY SortOrder, NameFa;
GO
